### ISSUE TITLE
importing Conv2D from keras

### ISSUE THREAD

**Issue by marioarrigonineri** [deeplearning4j/deeplearning4j#3105]
I'm attempting to import a pre-trained model into DL4J from keras.

However I get:

Unsupported keras layer type Conv2D. Please file an issue at http://github.com/deeplearning4j/deeplearning4j/issues.

I thought Conv2D was supported

**Comment by Miksu82** [comment]
I just had the same issue. It seems that current Keras model import doesn't work for if the model is trained with Keras 2.0 or above and  uses convolutional layers. 

From Keras 2.0 release notes:
> Convolution* layers are renamed Conv*.

https://github.com/fchollet/keras/wiki/Keras-2.0-release-notes

Then if you look at https://github.com/deeplearning4j/deeplearning4j/blob/deeplearning4j-0.8.0/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasLayer.java

lines 53-54,

```
public static final String LAYER_CLASS_NAME_CONVOLUTION_1D = "Convolution1D";
public static final String LAYER_CLASS_NAME_CONVOLUTION_2D = "Convolution2D";
```

So it looks like dl4j tries still uses the old Keras class names for those layers. Hopefully will get fixed in the next release. Meanwhile I think the only way to make the import work is to use older version of Keras to train the model.

**Comment by agibsonccc** [comment]
Just going to point out something kinda obvious here: The new keras spec is still HIGHLY unstable. You guys immediately moving to the latest and greatest is not something an actual company would do. Unfortunately that's who we target. I would prefer to wait for this to stabilize first.

Imagine being our shoes here. We have to both be backwards compatible *and* maintain the newer spec.
We will do that when  it stabilizes a bit. I talked to francois about this in SF a few weeks ago. It will take time to stabilize.

I know those of you in python land like instantly upgrading to the latest thing because you don't have to worry about backwards compatibility. Unfortunately we do. We will put resources in to this when it quits being as much of a moving target.

**Comment by turambar** [comment]
@marioarrigonineri @Miksu82 As you've noticed, Keras 2 isn't supported yet -- and Keras 2 made a lot of changes that break things, including both trivial changes (e.g., renaming `Convolution2D` layer to `Conv2D` -- whyyyyyyy?) and more substantive changes (e.g., changing the way weights are stored). We're still assessing the scope of the changes and planning our work. In the meantime, I'm going to add a version check and informative Exception about 2 not being supported yet.

For what it's worth, the [Keras model import code](https://github.com/deeplearning4j/deeplearning4j/tree/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras) is pretty easy to understand, and we'd be very happy to accept PRs from users like yourselves. Fully supporting Keras 2 will go much faster if our enthusiastic users help us pick off some of the low-hanging fruit (renamed layers, etc.). 

Adding support for layer named "Conv2D" shouldn't be too bad (with changes [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/layers/KerasConvolution.java) and [here](https://github.com/deeplearning4j/deeplearning4j/blob/master/deeplearning4j-modelimport/src/main/java/org/deeplearning4j/nn/modelimport/keras/KerasLayer.java#L216))

**Comment by turambar** [comment]
Given that this is Keras 2 related, I'm going to close it in favor of the more general Keras 2 support issue: https://github.com/deeplearning4j/deeplearning4j/issues/3129

**Comment by lechatthecat** [comment]
#3129 says it's done implementing keras2 support but I still get this error.

**Comment by agibsonccc** [comment]
Just use snapshots. http://deeplearning4j.org/snapshots  (as it says in the other issue)
