### ISSUE TITLE
DL4j Not Working with New Android Studio Gradle Plugin version 3.0.1

### ISSUE THREAD

**Issue by poweigel** [deeplearning4j/deeplearning4j#4330]
#### Issue Description
When the dl4j dependencies are included in Android Studio with gradle plugin 3.0.1, they result in the following error:

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

With the previous version of gradle plugin (2.3.3), this error does not occur and the project compiles.

#### Version Information

Deeplearning4j dependencies (and related dependencies) included in project:
org.deeplearning4j:deeplearning4j-core:0.9.1
org.nd4j:nd4j-native:0.9.1
org.nd4j:nd4j-native:0.9.1:android-x86
org.nd4j:nd4j-native:0.9.1:android-arm
org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-x86
org.bytedeco.javacpp-presets:openblas:0.2.19-1.3:android-arm

The project is being run on Windows 10 in Android Studio 3.0. Deeplearning4j version is 0.9.1.

#### Contributing

Recently, Android Studio's gradle plugin was upgraded to v 3.0.1. In this upgrade, per-class dexing was enabled to improve performance. This has the side-effect of causing an error when a project has identical dependencies calling different versions. I've manually gone through the dependencies tree for this project to locate identical versions with different versions but was unable to locate the culprit because of how many transitive dependencies there are. My guess is that either junit or hamcrest is the issue here.

For now my workaround is to run everything smoothly with the previous version of the gradle plugin (2.3.3) and gradle wrapper (3.3).

**Comment by saudet** [comment]
Thanks! Also, quoting you from Gitter:
> @saudet sure, here's the dependencies tree. i'm using gradle 3.0.1 and the only dl4j-related dependency i've added is org.deeplearning4j:deeplearning4j-core:0.9.1. https://gist.github.com/poweigel/1fd1e27c564008bb45f9ad7b4c2bebbb

**Comment by poweigel** [comment]
Yes, correct. Specifically the gradle plugin is version 3.0.1 and the gradle is version 4.1 when the error occurs. Here are the release notes from the Android Studio team:

https://developer.android.com/studio/releases/gradle-plugin.html

**Comment by saudet** [comment]
This is probably fixed with https://github.com/deeplearning4j/nd4j/pull/2798

Could you give it a try with 0.9.2-SNAPSHOT?

**Comment by jrmerwin** [comment]
Conflicting versions of org.apache.commons:commons are present 

+--- com.android.support:appcompat-v7:27.0.2
|    +--- com.android.support:support-annotations:27.0.2
|    +--- com.android.support:support-core-utils:27.0.2
|    |    +--- com.android.support:support-annotations:27.0.2
|    |    \--- com.android.support:support-compat:27.0.2
|    |         +--- com.android.support:support-annotations:27.0.2
|    |         \--- android.arch.lifecycle:runtime:1.0.3
|    |              +--- android.arch.lifecycle:common:1.0.3
|    |              \--- android.arch.core:common:1.0.0
|    +--- com.android.support:support-fragment:27.0.2
|    |    +--- com.android.support:support-compat:27.0.2 (*)
|    |    +--- com.android.support:support-core-ui:27.0.2
|    |    |    +--- com.android.support:support-annotations:27.0.2
|    |    |    \--- com.android.support:support-compat:27.0.2 (*)
|    |    +--- com.android.support:support-core-utils:27.0.2 (*)
|    |    \--- com.android.support:support-annotations:27.0.2
|    +--- com.android.support:support-vector-drawable:27.0.2
|    |    +--- com.android.support:support-annotations:27.0.2
|    |    \--- com.android.support:support-compat:27.0.2 (*)
|    \--- com.android.support:animated-vector-drawable:27.0.2
|         +--- com.android.support:support-vector-drawable:27.0.2 (*)
|         \--- com.android.support:support-core-ui:27.0.2 (*)
+--- com.android.support:design:27.0.2
|    +--- com.android.support:support-v4:27.0.2
|    |    +--- com.android.support:support-compat:27.0.2 (*)
|    |    +--- com.android.support:support-media-compat:27.0.2
|    |    |    +--- com.android.support:support-annotations:27.0.2
|    |    |    \--- com.android.support:support-compat:27.0.2 (*)
|    |    +--- com.android.support:support-core-utils:27.0.2 (*)
|    |    +--- com.android.support:support-core-ui:27.0.2 (*)
|    |    \--- com.android.support:support-fragment:27.0.2 (*)
|    +--- com.android.support:appcompat-v7:27.0.2 (*)
|    +--- com.android.support:recyclerview-v7:27.0.2
|    |    +--- com.android.support:support-annotations:27.0.2
|    |    +--- com.android.support:support-compat:27.0.2 (*)
|    |    \--- com.android.support:support-core-ui:27.0.2 (*)
|    \--- com.android.support:transition:27.0.2
|         +--- com.android.support:support-annotations:27.0.2
|         \--- com.android.support:support-compat:27.0.2 (*)
+--- org.deeplearning4j:deeplearning4j-nn:1.0.0-alpha
|    +--- org.deeplearning4j:deeplearning4j-utility-iterators:1.0.0-alpha
|    |    +--- org.deeplearning4j:deeplearning4j-util:1.0.0-alpha
|    |    |    +--- org.nd4j:nd4j-api:1.0.0-alpha
|    |    |    |    +--- org.apache.commons:commons-math3:3.4.1
|    |    |    |    +--- com.vlkan:flatbuffers:1.2.0-3f79e055
|    |    |    |    +--- com.github.os72:protobuf-java-shaded-351:0.9
|    |    |    |    +--- com.github.os72:protobuf-java-util-shaded-351:0.9
|    |    |    |    |    +--- com.github.os72:protobuf-java-shaded-351:0.9
|    |    |    |    |    +--- com.google.guava:guava:19.0
|    |    |    |    |    \--- com.google.code.gson:gson:2.7
|    |    |    |    +--- uk.com.robust-it:cloning:1.9.3
|    |    |    |    |    \--- org.objenesis:objenesis:2.1 -> 2.6
|    |    |    |    +--- org.slf4j:slf4j-api:1.7.10
|    |    |    |    +--- org.nd4j:jackson:1.0.0-alpha
|    |    |    |    |    +--- org.yaml:snakeyaml:1.12
|    |    |    |    |    +--- org.codehaus.woodstox:stax2-api:3.1.4
|    |    |    |    |    \--- joda-time:joda-time:2.2 -> 2.9.2
|    |    |    |    +--- org.nd4j:nd4j-buffer:1.0.0-alpha
|    |    |    |    |    +--- org.nd4j:nd4j-context:1.0.0-alpha
|    |    |    |    |    |    \--- org.nd4j:nd4j-common:1.0.0-alpha
|    |    |    |    |    |         +--- org.nd4j:jackson:1.0.0-alpha (*)
|    |    |    |    |    |         +--- org.slf4j:slf4j-api:1.7.10
|    |    |    |    |    |         +--- org.reflections:reflections:0.9.10
|    |    |    |    |    |         |    +--- com.google.guava:guava:18.0 -> 19.0
|    |    |    |    |    |         |    \--- org.javassist:javassist:3.18.2-GA
|    |    |    |    |    |         +--- commons-io:commons-io:2.4
|    |    |    |    |    |         +--- org.apache.commons:commons-math3:3.4.1
|    |    |    |    |    |         +--- org.apache.commons:commons-lang3:3.3.1
|    |    |    |    |    |         \--- org.apache.commons:commons-compress:1.16.1
|    |    |    |    |    |              \--- org.objenesis:objenesis:2.6
|    |    |    |    |    \--- org.bytedeco:javacpp:1.4.1
|    |    |    |    +--- org.nd4j:nd4j-context:1.0.0-alpha (*)
|    |    |    |    +--- net.ericaro:neoitertools:1.0.0
|    |    |    |    \--- org.reflections:reflections:0.9.10 (*)
|    |    |    \--- org.nd4j:nd4j-common:1.0.0-alpha (*)
|    |    +--- org.deeplearning4j:deeplearning4j-datasets:1.0.0-alpha
|    |    |    \--- org.deeplearning4j:deeplearning4j-datavec-iterators:1.0.0-alpha
|    |    |         +--- org.datavec:datavec-api:1.0.0-alpha
|    |    |         |    +--- org.jetbrains:annotations:13.0
|    |    |         |    +--- org.apache.commons:commons-compress:1.8.1 -> 1.16.1 (*)
|    |    |         |    +--- org.apache.commons:commons-lang3:3.3.1
|    |    |         |    +--- org.apache.commons:commons-math3:3.3 -> 3.4.1
|    |    |         |    +--- commons-io:commons-io:2.4
|    |    |         |    +--- commons-codec:commons-codec:1.10
|    |    |         |    +--- org.slf4j:slf4j-api:1.7.7 -> 1.7.10
|    |    |         |    +--- joda-time:joda-time:2.9.2
|    |    |         |    +--- org.nd4j:jackson:1.0.0-alpha (*)
|    |    |         |    +--- org.freemarker:freemarker:2.3.23
|    |    |         |    +--- org.reflections:reflections:0.9.10 (*)
|    |    |         |    +--- org.nd4j:nd4j-common:1.0.0-alpha (*)
|    |    |         |    +--- org.nd4j:nd4j-api:1.0.0-alpha (*)
|    |    |         |    +--- com.clearspring.analytics:stream:2.7.0
|    |    |         |    |    \--- it.unimi.dsi:fastutil:6.5.7
|    |    |         |    +--- net.sf.opencsv:opencsv:2.3
|    |    |         |    +--- com.tdunning:t-digest:3.2
|    |    |         |    \--- org.eclipse.collections:eclipse-collections:9.1.0
|    |    |         |         \--- org.eclipse.collections:eclipse-collections-api:9.1.0
|    |    |         \--- org.nd4j:nd4j-api:1.0.0-alpha (*)
|    |    \--- org.nd4j:nd4j-api:1.0.0-alpha (*)
|    +--- commons-io:commons-io:2.4
|    +--- org.nd4j:nd4j-api:1.0.0-alpha (*)
|    +--- org.nd4j:nd4j-common:1.0.0-alpha (*)
|    +--- org.nd4j:jackson:1.0.0-alpha (*)
|    +--- org.nd4j:nd4j-jackson:1.0.0-alpha
|    |    +--- org.nd4j:nd4j-base64:1.0.0-alpha
|    |    |    +--- org.nd4j:nd4j-api:1.0.0-alpha (*)
|    |    |    \--- commons-net:commons-net:3.1
|    |    \--- org.nd4j:jackson:1.0.0-alpha (*)
|    +--- org.apache.commons:commons-compress:1.8 -> 1.16.1 (*)
|    \--- org.threadly:threadly:4.10.0
+--- org.nd4j:nd4j-native:1.0.0-alpha
|    +--- org.bytedeco:javacpp:1.4.1
|    +--- org.bytedeco.javacpp-presets:openblas:0.2.20-1.4.1
|    |    \--- org.bytedeco:javacpp:1.4.1
|    +--- org.bytedeco.javacpp-presets:mkl:2018.1-1.4.1
|    |    \--- org.bytedeco:javacpp:1.4.1
|    +--- org.nd4j:nd4j-native-api:1.0.0-alpha
|    |    +--- org.nd4j:nd4j-buffer:1.0.0-alpha (*)
|    |    +--- org.nd4j:nd4j-api:1.0.0-alpha (*)
|    |    \--- org.bytedeco:javacpp:1.4.1
|    \--- org.nd4j:nd4j-api:1.0.0-alpha (*)
+--- org.bytedeco.javacpp-presets:openblas:0.2.20-1.4.1 (*)
\--- com.google.code.findbugs:annotations:3.0.1

**Comment by saudet** [comment]
@jrmerwin Should be fixed now. Could you try with 1.0.0-SNAPSHOT? To get Gradle working with snapshots, we'll need to run a dummy Maven project before. Create the following `pom.xml` file and run `mvn compile` on it. That will download all the artifacts we need in `~/.m2` and Gradle will be able to pick them up from there with `repositories {  mavenLocal()  }` in the `build.gradle` file. BTW, this is something to add to the documentation!

```xml
<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>org.deeplearning4j</groupId>
    <artifactId>snapshots</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <dependencies>
       <dependency>
            <groupId>org.nd4j</groupId>
            <artifactId>nd4j-native-platform</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>org.deeplearning4j</groupId>
            <artifactId>deeplearning4j-core</artifactId>
            <version>1.0.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <repositories>
        <repository>
            <id>sonatype-nexus-snapshots</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
            <snapshots>
                <enabled>true</enabled>
                <updatePolicy>always</updatePolicy>
            </snapshots>
        </repository>
    </repositories>
</project>
```

**Comment by jrmerwin** [comment]
I added the pom file, ran mvn compile and changed the dependency to org.deeplearning4j:deeplearning4j-nn:1.0.0-SNAPSHOT. This error occurred during the build:

Error:Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
> java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Unable to merge dex

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535

**Comment by saudet** [comment]
Reinstalling everything (JDK, SDK, IDE, etc) and recreating the project files from scratch usually fixes these kinds of errors: https://stackoverflow.com/questions/37772799/errorexecution-failed-for-task-appmergedebugresources-java-lang-arrayind
That's basically how Android "works"...

**Comment by jrmerwin** [comment]
I tried reinstalling everything, JDK, SDK, etc., rebuilt the demo from scratch, added the pom file and mvn compile, cleaned and rebuilt a few times. Still getting the dex merge errors during the gradle build.
 ```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
 
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\0.jar…..
 ```
Then goes on to give the same error for 102 jar files.

**Comment by saudet** [comment]
Thanks! Is it still complaining about `Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535` or is it giving another cause now?

**Comment by jrmerwin** [comment]
I don't see the out of bounds anymore, just the Error while merging dex archives error.

**Comment by saudet** [comment]
Ok, could you post the full error log of ~100 lines?

**Comment by jrmerwin** [comment]
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\0.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\59.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\62.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\68.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\69.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\73.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\79.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\80.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\81.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\82.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\83.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\84.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\85.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\86.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\87.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\88.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\89.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\90.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\91.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\92.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\93.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\94.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\95.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\96.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\97.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\98.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\99.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\100.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\101.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\102.jar
at com.android.builder.profile.Recorder$Block.handleException(Recorder.java:55)
at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:104)
at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
... 32 more
Caused by: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\0.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\1.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\2.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\3.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\4.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\5.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\6.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\7.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\8.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\9.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\10.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\11.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\12.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\13.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\14.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\15.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\16.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\17.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\18.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\19.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\20.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\22.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\23.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\25.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\27.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\28.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\30.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\34.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\35.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\36.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\37.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\38.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\39.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\40.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\41.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\42.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\43.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\44.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\45.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\46.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\47.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\48.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\49.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\50.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\51.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\52.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\53.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\54.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\55.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\56.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\57.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\58.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\59.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\60.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\61.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\62.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\63.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\64.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\65.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\66.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\67.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\68.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\69.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\70.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\71.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\72.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\73.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\74.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\75.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\76.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\77.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\78.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\79.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\80.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\81.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\82.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\83.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\84.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\85.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\86.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\87.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\88.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\89.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\90.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\91.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\92.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\93.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\94.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\95.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\96.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\97.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\98.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\99.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\100.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\101.jar, C:\Users\JasonM\Desktop\demo_progur_rebuild\app\build\intermediates\transforms\dexBuilder\debug\102.jar
at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:124)
at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:109)
at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
... 48 more
Caused by: com.android.tools.r8.CompilationFailedException: Compilation failed to complete
at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:76)
at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
at com.android.tools.r8.D8.run(D8.java:67)
at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
... 53 more
Caused by: com.android.tools.r8.utils.AbortException
at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:77)
at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:58)
at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:67)
... 56 more
```

**Comment by saudet** [comment]
Are you still using `classpath 'com.android.tools.build:gradle:3.0.1'`? If so, try to upgrade to 3.1.0. It seems to fix a lot of things: https://developer.android.com/studio/releases/gradle-plugin#3-1-0

**Comment by jrmerwin** [comment]
Interesting... I had it set to 3.1.2 after reinstalling everything. Reverting it to 3.1.0 got the out of bounds error to come back. I suspect it might be downstream of the other dex error I was getting. Here is the out of bounds error I am seeing with 3.0.1                         
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:100)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:70)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:60)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:97)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:87)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.run(DefaultTaskGraphExecuter.java:248)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:241)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:230)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.processTask(DefaultTaskPlanExecutor.java:123)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.access$200(DefaultTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:104)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:98)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.execute(DefaultTaskExecutionPlan.java:626)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionPlan.executeWithTask(DefaultTaskExecutionPlan.java:581)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$TaskExecutorWorker.run(DefaultTaskPlanExecutor.java:98)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by jrmerwin** [comment]
```
Caused by: java.lang.ArrayIndexOutOfBoundsException: 65535
	at com.android.tools.r8.graph.OffsetToObjectMapping.getMethod(OffsetToObjectMapping.java:104)
	at com.android.tools.r8.dex.DexFileReader.methodHandleAt(DexFileReader.java:960)
	at com.android.tools.r8.dex.DexFileReader.populateMethodHandles(DexFileReader.java:853)
	at com.android.tools.r8.dex.DexFileReader.populateIndexTables(DexFileReader.java:838)
	at com.android.tools.r8.dex.ApplicationReader$ClassReader.readDexSources(ApplicationReader.java:206)
	at com.android.tools.r8.dex.ApplicationReader$ClassReader.readSources(ApplicationReader.java:253)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:114)
	at com.android.tools.r8.dex.ApplicationReader.read(ApplicationReader.java:86)
	at com.android.tools.r8.D8.run(D8.java:156)
	at com.android.tools.r8.D8.lambda$run$1(D8.java:91)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:58)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:45)
	at com.android.tools.r8.D8.run(D8.java:88)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:107)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.ExternalLibsMergerTransform.transform(ExternalLibsMergerTransform.kt:123)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:221)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:217)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:212)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:46)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:121)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:110)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:92)
	... 32 more
```

**Comment by saudet** [comment]
Where did you version 3.1.2 of the Gradle Plugin??

**Comment by saudet** [comment]
Ah, seems to have been released last week or so. Just use 3.1.0 please, don't go back to 3.0.1. What error do you get with 3.1.0?

**Comment by jrmerwin** [comment]
3.1.0 produced the above, Caused by out of bounds 65535 error.  I will keep it at 3.1.0 going forward.

**Comment by saudet** [comment]
And the same exact project works if you change the versions for
deeplearning4j back to 0.9.1?

**Comment by jrmerwin** [comment]
That is a great question. In order to get that exact project to run I had to do a the following:
 
I changed the dependencies back to 0.9.1
I reverted back to classpath 'com.android.tools.build:gradle:3.0.1'
And rolled back the minimum SDK to 23
 
Not doing any of these things causes the dex error during compile. Doing all three launches the app and it successfully completes:
 
```
04-28 00:17:34.397 23416-23460/com.example.jmerwin.demo_progur_rebuild D/MainActivity: output = ===========INPUT===================
    [[0.00,  0.00],  
     [0.00,  1.00],  
     [1.00,  0.00],  
     [1.00,  1.00]]
    =================OUTPUT==================
    [0.00,  1.00,  1.00,  0.00]
```

**Comment by saudet** [comment]
I'm assuming it also works fine with  'com.android.tools.build:gradle:3.1.0'?
Ok, something big changed in the dependencies...

**Comment by jrmerwin** [comment]
I just tried it again and can confirm that it will not compile with 
classpath 'com.android.tools.build:gradle:3.1.0'
it give the dex error

**Comment by saudet** [comment]
Ok, what about 3.1.2?

**Comment by jrmerwin** [comment]
3.1.2 gives the dex error as well

**Comment by saudet** [comment]
And what does 3.0.1 gives with 1.0.0-SNAPSHOT again? Did we test that?

Looking at the dependencies, threadly is the biggest difference I can see with 0.9.1. 
@jentfoo Has Threadly ever been tested on Android?

**Comment by jrmerwin** [comment]
I’m really glad you asked that question. Using the 1.0.0 snapshot with 3.0.1 just now got past the dex error and launched the app. It then crashed from with a NoSuchMethodError when it tried to build the Network at this line in the MainActivity: 

```
MultiLayerNetwork myNetwork = new MultiLayerNetwork(listBuilder.build());
```
The full error is here:
```
java.lang.NoSuchMethodError: No interface method applySchedules(ID)V in class Lorg/nd4j/linalg/learning/config/IUpdater; or its super classes (declaration of 'org.nd4j.linalg.learning.config.IUpdater' appears in /data/app/com.example.jmerwin.demo_progur_rebuild-BssZSquX4qS6t-rcorzkgQ==/split_lib_dependencies_apk.apk)
```

**Comment by saudet** [comment]
Oh, great. The NoSuchMethodError is probably caused by an old version of DL4J creeping in somehow. Check the dependency tree again to make sure everything's at 1.0.0-SNAPSHOT.

**Comment by saudet** [comment]
Hum, in any case, could your project files available somewhere, possibly on your fork of dl4j-examples?

**Comment by jentfoo** [comment]
@saudet It seems you have already figured out it's not related.  I am sorry it took me so long to reply, things have been crazy busy on my end.  I figured I would go ahead and answer your question though.

Threadly in the past has been used on android, as well as avian.  Though they are fairly niche uses of threadly, so there is always the potential for some unreported issues.  Threadly is not doing anything that I know would be problematic, I expect most, if not all, to work just fine.  All that said, if you do run into issues just let me know.  I will be happy to try and provide prompt fixes if we find any deficiencies.

**Comment by saudet** [comment]
@jentfoo Thanks! Good to know. We're trying to figure out the build issue, haven't had time to look into it, but knowing that it's probably not Threadly helps.

**Comment by saudet** [comment]
@jrmerwin I've narrowed down the issue to eclipse-collections. After merging the pull requests above, the following builds without problems:
```groovy
    compile (group: 'org.deeplearning4j', name: 'deeplearning4j-nn', version: '1.0.0-SNAPSHOT') {
        exclude group: 'org.bytedeco.javacpp-presets', module: 'opencv-platform'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'leptonica-platform'
        exclude group: 'org.bytedeco.javacpp-presets', module: 'hdf5-platform'
    }
    compile group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-SNAPSHOT'
    compile group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-SNAPSHOT', classifier: "android-arm"
    compile group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-SNAPSHOT', classifier: "android-arm64"
    compile group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-SNAPSHOT', classifier: "android-x86"
    compile group: 'org.nd4j', name: 'nd4j-native', version: '1.0.0-SNAPSHOT', classifier: "android-x86_64"
    compile group: 'org.bytedeco.javacpp-presets', name: 'openblas', version: '0.2.20-1.4.1', classifier: "android-arm"
    compile group: 'org.bytedeco.javacpp-presets', name: 'openblas', version: '0.2.20-1.4.1', classifier: "android-arm64"
    compile group: 'org.bytedeco.javacpp-presets', name: 'openblas', version: '0.2.20-1.4.1', classifier: "android-x86"
    compile group: 'org.bytedeco.javacpp-presets', name: 'openblas', version: '0.2.20-1.4.1', classifier: "android-x86_64"
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: "android-arm"
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: "android-arm64"
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: "android-x86"
    compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.4.1-1.4.1', classifier: "android-x86_64"
```
Please let me know if you encounter any other issues! Thanks

**Comment by jrmerwin** [comment]
@saudet Thanks for your work on this. I will give the above a try and update the docs.
