### ISSUE TITLE
Word2VecRawTextExample Cannot perform in-place operation "muli": result array shape does not match the broadcast operation output shape

### ISSUE THREAD

**Issue by leeharland** [deeplearning4j/deeplearning4j#8288]
#### Issue Description

Please describe our issue, along with:
Running unadulterated Word2VecRawTextExample

Exception in thread "main" java.lang.IllegalStateException: Cannot perform in-place operation "muli": result array shape does not match the broadcast operation output shape: [100].muli([1, 100]) != [100].
In-place operations like x.muli(y) can only be performed when x and y have the same shape, or x and y are broadcastable with x.shape() == broadcastShape(x,y)
	at org.nd4j.linalg.api.shape.Shape.assertBroadcastable(Shape.java:283)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3235)
	at org.nd4j.linalg.api.ndarray.BaseNDArray.muli(BaseNDArray.java:3229)
	at org.deeplearning4j.models.embeddings.reader.impl.BasicModelUtils.wordsNearestSum(BasicModelUtils.java:354)
	at org.deeplearning4j.models.embeddings.reader.impl.BasicModelUtils.wordsNearestSum(BasicModelUtils.java:232)
	at org.deeplearning4j.models.embeddings.wordvectors.WordVectorsImpl.wordsNearestSum(WordVectorsImpl.java:149)
	at org.deeplearning4j.examples.nlp.word2vec.Word2VecRawTextExample.main(Word2VecRawTextExample.java:83)
#### Version Information

Please indicate relevant versions, including, if relevant:

* Deeplearning4j version
 - latest (cloned 14/10/19)
* Platform information (OS, etc)
 - OSX10.14.2  jdk1.8.0.202 

Thanks!

**Comment by raver119** [comment]
Fixed. Thanks for highlighting this problem.

**Comment by leeharland** [comment]
fabulous, thanks for fixing it so quickly :)

**Comment by raver119** [comment]
Unfortunately you’ll have to wait couple of days till fix gets into snapshots.

**Comment by luisgarcc** [comment]
I am running against 1.0.0-SNAPSHOTs and I keep seeing the same error. Did this make it into the builds yet?

**Comment by maiger77** [comment]
I'am still having this problem during running the word2vec example code
could you help me?

**Comment by AlexDBlack** [comment]
@maiger77 if you're running 1.0.0-beta5, that's expected
You'll need to switch to snapshots to get the fix (at least until the next release)
You can find instructions here:
https://deeplearning4j.org/docs/latest/deeplearning4j-config-snapshots

Or are you on the latest snapshots already?

**Comment by Ghulam-Sarwar** [comment]
@AlexDBlack I tried to follow the instructions to run on 1.0.0-SNAPSHOT as well. I am facing the same issue. Any help would be great.

**Comment by AlexDBlack** [comment]
@Ghulam-Sarwar Are you seeing this on Word2VecRawTextExample? Or somewhere else?
The current/latest version of the examples (using 1.0.0-beta6), Word2VecRawTextExample runs without any problems for me (I just checked again now). Make sure to pull the latest version of the examples before trying again.

If it's somewhere else (not that example), then getting that exception it most likely means the error is correct - i.e., the operation isn't valid. For example, trying to add 2 arrays with shapes like [3,4] and [5,6], that can't be done due to the incompatible shapes.
